# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08c49d605aeba37cf6554f61d83c70ac026e8664b93c2b428839bedbafac734ee45f8a3efc5729096b551f4c3481d008b1bfb84df6a83aed411104569d2edf8f

test:
  secret_key_base: 7f749e825c9e45282ff4fb8797b956234e1c6eaec469764e8ff2869deb08fa6d85f857ab51168d8d0a02f875a740ae9c3e4d029c382ce9f8fbb3cbfd7c1b2be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
